<a href="https://colab.research.google.com/github/nedokormysh/GB_Libraries_python_for_DS/blob/lesson1-2/Libraries_python_DS_HW_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**Тема “Вычисления с помощью Numpy”**

**Задание 1**

Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.



In [ ]:
# a = [[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]]
# a = np.array(a).T
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

**Задание 2**

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [ ]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

**Задание 3**

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [ ]:
a_centered_sp = np.dot(a_centered[:, 0].T, a_centered[:, 1])
# a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
N = a.shape[0]
a_centered_sp = a_centered_sp / (N - 1)
a_centered_sp

2.0

**Задание 4**

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [ ]:
np.cov(a.T)[0, 1]

2.0

**Задание 5**

Необходимо реализовать метод сортировки целых (int) элементов. Метод должен быть реализован без использования “готовых” методов ( sorted, np.sort() ).

In [ ]:
a = [2, 3, 4 , 8, 1]
a = np.array(a)

n = a.shape[0]

for i in range(1, n):
  for j in range(i, 0, -1):
    if a[j] < a[j - 1]:
      a[j], a[j - 1] = a[j - 1], a[j]
a

array([1, 2, 3, 4, 8])

**Тема “Работа с данными в Pandas”**

**Задание 1**

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].

In [ ]:
import pandas as pd

In [ ]:
# author_id = [1, 2, 3]
# authors = pd.DataFrame(author_id, index=['Тургенев', 'Чехов', 'Островский'])
authors = pd.DataFrame({'author_id': [1, 2, 3], 'author_name': ['Тургенев', 'Чехов', 'Островский']})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [ ]:
 book = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3], 
                      'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 
                      'price': [450, 300, 350, 500, 450, 370, 290]})
 book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

**Задание 2**

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [ ]:
authors_price = pd.merge(authors, book, on='author_id', how='outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

**Задание 3**

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [ ]:
top5 = authors_price.nlargest(5, 'price')
top5 = top5.reset_index()
top5

index  author_id author_name         book_title  price
0      3          2       Чехов   Толстый и тонкий    500
1      0          1    Тургенев        Отцы и дети    450
2      4          2       Чехов    Дама с собачкой    450
3      5          3  Островский              Гроза    370
4      2          1    Тургенев  Дворянское гнездо    350

**Задание 4**

Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

In [ ]:
# authors_stats = authors_price.groupby('author_name').agg({'price':['max','min','mean']})
# authors_stats = authors_stats.rename(columns = {'max': 'max_price', 'min': 'min_price', 'mean': 'mean_price'})
authors_stat = authors_price.groupby('author_name').agg({'price': 
                                                         [('min_price', 'min'), 
                                                          ('max_price', 'max'), 
                                                          ('mean_price', 'mean')]})

authors_stat

price                      
            min_price max_price  mean_price
author_name                                
Островский        290       370  330.000000
Тургенев          300       450  366.666667
Чехов             450       500  475.000000

**Задание 5***

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].

Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.

Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [ ]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [ ]:
book_info = pd.pivot_table(authors_price, values='price', index='author_name', columns='cover', aggfunc='sum', fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [ ]:
book_info.to_pickle("book_info.pkl")
book_info2 = pd.read_pickle("book_info.pkl")
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [ ]:
book_info.equals(book_info2)

True

**Задание 5** ** 

Вычисление метрик для мониторинга.

суммарная выручка

кол-во покупок

средний чек

среднее кол-во товаров в покупке

Дополнительно добавим возможность фильтровать данные по различным параметрам. Это может быть полезно чтобы посмотреть как меняются продажи в двух группах, или в какой-то отдельной категории товаров.

На вход функции будет подаваться датафрейм с данными о продажах, словарь с фильтрами и период, за который нужно посчитать метрики.
Функция должна вернуть датафрейм, в индексах которого будут все даты из указанного периода отсортированные по возрастанию, а столбцы - метрики ['revenue', 'number_purchases', 'average_check', 'average_number_items']. Формат данных столбцов - float, формат данных индекса - datetime64[ns].
Если в какие-то дни не было продаж, то нужно заполнить пропуск нулём.

import numpy as np
import pandas as pd
def calculate_sales_metrics(df, cost_name, date_name, sale_id_name, period, filters=None):
   """Вычисляет метрики по продажам.
   df - pd.DataFrame, датафрейм с данными. Пример
       pd.DataFrame(
           [[820, '2021-04-03', 1, 213]],
           columns=['cost', 'date', 'sale_id', 'shop_id']
       )
   cost_name - str, название столбца с стоимостью товара
   date_name - str, название столбца с датой покупки
   sale_id_name - str, название столбца с идентификатором покупки (в одной покупке может быть несколько товаров)
   period - dict, словарь с датами начала и конца периода пилота.
       Пример, {'begin': '2020-01-01', 'end': '2020-01-08'}.
       Дата начала периода входит в полуинтервал, а дата окончания нет,
       то есть '2020-01-01' <= date < '2020-01-08'.
   filters - dict, словарь с фильтрами. Ключ - название поля, по которому фильтруем, значение - список значений,
       которые нужно оставить. Например, {'user_id': [111, 123, 943]}.
       Если None, то фильтровать не нужно.
   return - pd.DataFrame, в индексах все даты из указанного периода отсортированные по возрастанию,
       столбцы - метрики ['revenue', 'number_purchases', 'average_check', 'average_number_items'].
       Формат данных столбцов - float, формат данных индекса - datetime64[ns].
   """
   # YOUR_CODE_HERE



In [ ]:
dict_for_metrics = {'cost': [820, 180, 350, 690, 510, np.nan], 
                    'date': ['2021-04-03', '2021-04-03', '2021-05-13', '2020-08-26', '2019-04-03', '2018-04-03'], 
                    'sales_id': [1, 2, 3, 4, 5, np.nan], 
                    # 'sales_id': np.arange(6),
                    'shop_id': [213, 518, 687, 101, 656, np.nan], 
                    'quantity_of_products': [8, 9, 10, 11, 12, np.nan]}

df_for_metrics = pd.DataFrame(dict_for_metrics)
df_for_metrics

cost        date  sales_id  shop_id  quantity_of_products
0  820.0  2021-04-03       1.0    213.0                   8.0
1  180.0  2021-04-03       2.0    518.0                   9.0
2  350.0  2021-05-13       3.0    687.0                  10.0
3  690.0  2020-08-26       4.0    101.0                  11.0
4  510.0  2019-04-03       5.0    656.0                  12.0
5    NaN  2018-04-03       NaN      NaN                   NaN

In [ ]:
di_period = {'begin': '2018-01-01', 'end': '2021-05-13'}
di_filters = {'quantity_of_products': [11, 30, 12, 17]}

In [132]:
def calculate_sales_metrics(df, period, filters=None):

  df_return_of_metrics = df
  
  df['date'] = pd.to_datetime(df.date)

  df['revenue'] = df['cost'] * df['quantity_of_products']
  df = df[(df['date'] >= period['begin']) & (df['date'] < period['end'])]
  df = df.groupby('date').agg({'revenue': np.sum,
                               'sales_id': 'count',
                               'quantity_of_products': np.sum})
    
  df = df.rename(columns = {'sales_id': 'number_of_purchases'})
  df['average check'] = df['revenue'] / df['number_of_purchases']
  df = pd.DataFrame(df, dtype='float64')
 
  # df = df.loc[df[filters.keys()].isin(filters.values()).all(axis=1), :]
 
  df = df.fillna(0)
  print(df.index)
  print(df.dtypes)
  
  # df = df.loc[period['begin']:period['end']]
   
  return df

In [133]:
calculate_sales_metrics(df_for_metrics, di_period, di_filters)

DatetimeIndex(['2018-04-03', '2019-04-03', '2020-08-26', '2021-04-03'], dtype='datetime64[ns]', name='date', freq=None)
revenue                 float64
number_of_purchases     float64
quantity_of_products    float64
average check           float64
dtype: object


revenue  number_of_purchases  quantity_of_products  average check
date                                                                         
2018-04-03      0.0                  0.0                   0.0            0.0
2019-04-03   6120.0                  1.0                  12.0         6120.0
2020-08-26   7590.0                  1.0                  11.0         7590.0
2021-04-03   8180.0                  2.0                  17.0         4090.0